server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecom
    driverClassName: org.postgresql.Driver
    username: dev
    password: dev123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: false
  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: DEBUG
